#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi


# Qt version (needs to be set so that qtchooser can run the correct qmake etc.)
export QT_SELECT=4
# Java
export JAVA_HOME="/usr/lib/jvm/java-openjdk"
