#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi


# Qt version (needs to be set so that qtchooser can run the correct qmake etc.)
export QT_SELECT=4
# Java
if [[ "$OSTYPE" == darwin* ]]; then
  # fails if there is no java installed; TODO uncomment when needed
  # export JAVA_HOME=$(/usr/libexec/java_home)
  export HOMEBREW_NO_AUTO_UPDATE=1
else
  export JAVA_HOME="/usr/lib/jvm/java-openjdk"
fi

# via https://dandavison.github.io/delta/tips-and-tricks/mouse-scrolling.html, had to add --mouse for scrolling
# less options:
  # -+S Wrap lines instead of the default chop-long-lines which breaks mouse select & copy in terminal (also, horizontal scrolling is annoying).
  # -F Quit if entire file fits on first screen. Otherwise have to press q.
  # -E Quit at end of file. E.g. when reaching it via G.
  # -R Output "raw" control characters.
  # -X Don't use init/deinit strings.
export DELTA_PAGER='less -RFXE --mouse'
export BAT_PAGER='less -RFX --mouse'
