#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

alias v='gvim -v'
alias packer='packer --noedit --noconfirm'
alias ocaml='rlwrap -H ~/.ocaml_history -D 2 -i -s 10000 ocamlfind batteries/ocaml'
function cwdsh(){ if [[ -z $2 ]]; then eval $1; else pu $2; eval $1; po; fi }
alias lh='cwdsh "ls -d .*"'
alias lah='cwdsh "ls -lhd .*"'
# unalias top # prezto aliases it to htop if it's installed
alias topm='\top -o %MEM'
function psmem(){ # e.g. psmem chrome
    \top -bn 1 | grep $1 | cut -c32-36 - | awk '{s+=$1} END {print s}'
}
function archive(){ # save file(s) as (encrypted) archive to dropbox
    dst=~/Dropbox/$1.7z
    rm -f $dst
    7z a -mhe=on -p -l $dst $* # if a password is given, the header will also be encrypted. resolves symlinks.
}
alias c='pygmentize -O style=monokai -f console256 -g'

function mkcd(){ mkdir -p $1; cd $1 }
alias cya='~/gitdrop.sh save && sudo pm-suspend'
alias utop='utop -require batteries -require cil'
function clip(){
    echo $* | xclip -selection clipboard
}
# alias tmux='TERM=screen-256color tmux'
alias pingor='ping -c 1 google.com || sudo systemctl restart dhcpcd@enp0s3.service'
